Feature
amklass11/awesome-books-es6 pull request #1
Opened 2022-05-04 18:49 UTC by amklass11

# es6 book app

1. modules created 
2. arrow  functions added
3. date added

2022-05-04 19:22 UTC, brytebee requested changes
Hi, @amklass11👋,

Good job so far coming so far with the progress you've made! 💪💪

## Highlights
You have done amazing in the following:
- Good set-up and use of modules in the project.✔️
- Great implementation of ES6 syntax.✔️
- Professionally looking project.✔️
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-04 19:22 UTC, brytebee commented on index.html
> +
- [ ] **Optional:** Kindly remove extra white lines. It is not professional to leave excess white lines beyond the required one for linters.

2022-05-04 19:22 UTC, brytebee commented on modules/Time.js
> +export { startTime, checkTime };
- [ ] **Required:** Excellent effort implementing the date/time yourself. 👏👏👏

However, it is a requirement to use `luxon` time library in this milestone. Kindly implement it and request another review.

![image](https://user-images.githubusercontent.com/27709832/166809753-b5c9c103-bb75-4e7c-9c97-9ee8d1aff17a.png)

2022-05-05 01:39 UTC, omar-labana commented
# **Approved ✔️**

Hi @amklass11

Congratulations on completing this project! 👏🏼 🎉

You have correctly implemented all of the requirements📃 correctly and without any errors⚠️ or bugs🪲.

Cheers and good luck in your next milestones! 🍀

Feel free to leave any questions or comments in the PR thread(don't forget to tag me 😄) if something is not 100% clear.

---
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 02:13 UTC, merged